version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=metro
      - MYSQL_DATABASE=metro
      - MYSQL_USER=metro
      - MYSQL_PASSWORD=metro
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  mysqltest:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=metro
      - MYSQL_DATABASE=metro
      - MYSQL_USER=metro
      - MYSQL_PASSWORD=metro
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/redis/conf.d

  supervisord:
    build:
      context: .
      dockerfile: supervisord/Dockerfile
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # config/logs
      - ./supervisord/conf:/etc/supervisord.d
      - ./supervisord/logs:/var/log/supervisor
    depends_on:
      - frontend
